# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='position',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='end_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Account'),
        ),
        migrations.AddField(
            model_name='position',
            name='profit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
