# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160330_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='symboltype',
            name='currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Account'),
        ),
    ]
