# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160402_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='closing_way',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='value',
            field=models.FloatField(),
        ),
    ]
