# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_account_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='profit',
            field=models.FloatField(null=True),
        ),
    ]
